apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: wis2obsproc-cluster
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: m5.xlarge
    desiredCapacity: 3
    volumeSize: 100