version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  producer:
    build: wis2bridge/.
    volumes:
      - ./wis2bridge:/app
    environment:
      - KAFKA_BROKER=kafka:9092
      - TOPICS=cache/a/wis2/+/+/data/core/weather/surface-based-observations/synop,cache/a/wis2/+/data/core/weather/surface-based-observations/synop
      - WIS_BROKER_HOST=globalbroker.meteo.fr
      - WIS_BROKER_PORT=8883
      - WIS_USERNAME=everyone
      - WIS_PASSWORD=everyone
      - VALIDATE_SSL=True 
      - LOG_LEVEL=INFO
      - KAFKA_TOPIC=notifications
      - REPORTING_THRESHOLD=500
      - BATCH_SIZE=50
      - CLIENT_ID=wis2bridge_test_

    depends_on:
      - kafka
    tty: true

  consumer:
    build: consumer/.
    volumes:
      - ./consumer:/app
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=notifications
      - KAFKA_PUBTOPIC=notifications-dedup
      - LOG_LEVEL=DEBUG
    depends_on:
      - kafka
    tty: true