version: "3"
services:
  

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./test-broker:/etc/mosquitto
      - ./test-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    

  mqtt-producer:
    build: ./test-node/.

    volumes:
      - ./test-node:/app

    working_dir: /app
    command: bash publoop.sh

    depends_on:
      - mosquitto

    tty: true

    
