version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  producer:
    build: producer/.
    volumes:
      - ./producer:/app
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
    tty: true

  consumer:
    build: consumer/.
    volumes:
      - ./consumer:/app
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
    tty: true