apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  ports:
    - name: "0"
      port: 0
      targetPort: 0
    - name: "7071"
      port: 7071
      targetPort: 7071
  selector:
    io.kompose.service: kafka
status:
  loadBalancer: {}
