apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mqtt-producer
  name: mqtt-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mqtt-producer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/: "true"
        io.kompose.service: mqtt-producer
    spec:
      containers:
        - args:
            - bash
            - publoop.sh
          env:
            - name: CONTENT_INTEGRATED_RATE
              value: "0.2"
            - name: DUPLICATE_MAX_DELAY_MS
              value: "1000"
            - name: INTEGRITY_CHECKSUM_RATE
              value: "0.001"
            - name: INTEGRITY_LENGTH_CONTENT_RATE
              value: "0.001"
            - name: INTEGRITY_LENGTH_LINK_RATE
              value: "0.001"
            - name: INTEGRITY_PUBDATE_RATE
              value: "0.001"
            - name: INTEGRITY_SCHEMA_RATE
              value: "0.001"
            - name: MSG_RATE
              value: "10"
            - name: NR_CACHES
              value: "3"
            - name: NR_DUPLICATES_MAX
              value: "3"
            - name: NR_DUPLICATES_MIN
              value: "1"
          image: mqtt-producer
          name: mqtt-producer
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /app
              name: mqtt-producer-claim0
          workingDir: /app
      restartPolicy: Always
      volumes:
        - name: mqtt-producer-claim0
          persistentVolumeClaim:
            claimName: mqtt-producer-claim0
status: {}
